import Head from "next/head";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Sidebar from "@/components/layout/sidebar";
import { useState } from "react";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>

      <div className="min-h-screen bg-slate-700">
        <Sidebar />
        <main className="sm:ml-64 flex-grow h-screen bg-slate-700">
          <Component {...pageProps} />
        </main>
      </div>

      {/* <script src="../node_modules/flowbite/dist/flowbite.min.js"></script> */}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
    </>
  );
}
